Sharing240.scene: started adding projectile sharing mechanism
Can see remote balls. But currently only spwan for each shot, thus end up with many balls.
Also, need to stabalize spatial mesh so randomly created holes. 

Was getting errors trying to use Resources.Load(), so added a remoteProjectileTemplate object to ProjectileShooter_Shared instead
 
Was getting error:
ProjectileShared: ProjectileShooter_Shared: ShootProjectileLocally()
(Filename: C:/buildslave/unity/build/artifacts/generated/Metro/runtime/DebugBindings.gen.cpp Line: 51
Please include a GameObject for the cursor.
(Filename: C:/buildslave/unity/build/artifacts/generated/Metro/runtime/DebugBindings.gen.cpp Line: 51)

Fixed: was calling Awake() on a disabled component that that was halting with the complaint.

Was getting:
ProjectileShared: ProjectileShooter_Shared: ShootProjectileLocally()
(Filename: C:/buildslave/unity/build/artifacts/generated/Metro/runtime/DebugBindings.gen.cpp Line: 51)

Exception thrown: 'System.ArgumentException' in UnityEngine.dll
ArgumentException: The Object you want to instantiate is null.
   at UnityEngine.Object.Instantiate[T](T original)
   at ProjectileShooter_Shared.ShootProjectileLocally(Vector3 start, Vector3 direction, Single magnitude, Int64 OwningUser)
   at ProjectileShooter_Shared.ProjectileShooter_ProcessRemoteProjectile(NetworkInMessage msg)
   at CustomMessages.OnMessageReceived(NetworkConnection connection, NetworkInMessage msg)
   at HoloToolkit.Sharing.NetworkConnectionAdapter.OnMessageReceived(NetworkConnection connection, NetworkInMessage message)
   at HoloToolkit.Sharing.NetworkConnectionListener.SwigDirectorOnMessageReceived(IntPtr connection, IntPtr message)
   at HoloToolkit.Sharing.SharingClientPINVOKE.SharingManager_Update(HandleRef jarg1)
   at HoloToolkit.Sharing.SharingManager.Update()
   at HoloToolkit.Sharing.SharingStage.LateUpdate()
   at HoloToolkit.Sharing.SharingStage.$Invoke17(Int64 instance, Int64* args)
   at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance, Int64* args, IntPtr method) 
(Filename: <Unknown> Line: 0)

FIXED: stopped using Resources.Load()